manifest:
  remotes:
    - name: TRDotExe
      url-base: https://github.com/TRDotExe
  projects:
    - name: zmk
      remote: TRDotExe
      revision: main
      import: app/west.yml
  self:
    path: config
